PROCEDURE ACEPTA_FORZADAS IS

TYPE R_DISTRIBUIR IS RECORD--Se crea este tipo de variable para poder pasar los registros del bloque distribuir a el bloque b620psac.
     ( V_SUCURSAL F037LENT.CLUGENTR%TYPE,
       V_QUNIPEDI F620PSAC.QUNIPEDI%TYPE);
    
     
TYPE R_TABLA IS TABLE OF R_DISTRIBUIR
    INDEX BY BINARY_INTEGER;
CUR R_TABLA;
    
VN_RECORD NUMBER := 1;
VN_RECORDA NUMBER := 1;
V_XCENTAJE VARCHAR(1) := 'N';
VB_RECORD BOOLEAN := TRUE;
V_CREFEREN F620PSAC.CREFEREN%TYPE;
V_FCADUCID F620PSAC.FCADUCID%TYPE;
V_CNUMLOTE F620PSAC.CNUMLOTE%TYPE;
V_CVARLOGI F620PSAC.CVARLOGI%TYPE;
V_CINDUCON F620PSAC.CINDUCON%TYPE;
V_XESTRCVL F620PSAC.XESTRCVL%TYPE;
V_QUNIPEDI F620PSAC.QUNIPEDI%TYPE;
V_DESDE_FECHA DATE;
V_HASTA_FECHA DATE;
V_LOTE  F620PSAC.CNUMLOTE%TYPE;


V_DESCRIPCION F002ARTI_PLL.DARTIGDM%TYPE;
V_STOCK_REST NUMBER := 0;
V_STOCK_ORIG NUMBER := :B620PSAC.AUX_QUNIPEDI;
V_STOCK_PORS NUMBER := 0;
V_DISTRIBUIR_POR VARCHAR(1);

BEGIN
		
 	  	FIRST_RECORD;	
 	  	
 	  	
V_LOTE        :=	:B620PSAC.AUX_LOTE;
V_DESDE_FECHA :=  :B620PSAC.DESDE_FECHA;
V_HASTA_FECHA :=  :B620PSAC.HASTA_FECHA;
V_DESCRIPCION := :B620PSAC.DESCRIPCION;
 		    


							 	   	 
                    CUR(VN_RECORD).V_SUCURSAL := :DISTRIBUIR.DIST_CLUGENTR;
                    CUR(VN_RECORD).V_QUNIPEDI := :DISTRIBUIR.DIST_CANTIDA_FORZADA;
                     				 
                    :B620PSAC.AUX_CLUGENTR := CUR(VN_RECORDA).V_SUCURSAL;
                    -- Guardo los registros 
                    V_CREFEREN := :B620PSAC.AUX_CREFEREN;	
                    V_FCADUCID := :B620PSAC.AUX_FCADUCID;
                    V_CNUMLOTE := :B620PSAC.AUX_CNUMLOTE;
                    V_CVARLOGI := :B620PSAC.AUX_CVARLOGI;
                    V_CINDUCON := :B620PSAC.AUX_CINDUCON;
                    V_XESTRCVL := :B620PSAC.AUX_XESTRCVL;
                    V_QUNIPEDI := :B620PSAC.AUX_QUNIPEDI;
                    V_STOCK_REST := :B620PSAC.DIST_STOCK_RESTANTE;
                    :B620PSAC.DESCRIPCION := V_DESCRIPCION;
                    
                    :B620PSAC.AUX_QUNIPEDI := CUR(VN_RECORDA).V_QUNIPEDI;
                    V_DISTRIBUIR_POR := :DISTRIBUIR_POR;
	
					
					COMPLETA_SUCURSAL;
				  
			

                    IF V_STOCK_REST <> 0  THEN -- Si hay stock restante inserta un registro con ese stock.
                        
                       
                        :B620PSAC.AUX_QUNIPEDI := V_STOCK_REST;             
                        :B620PSAC.AUX_CREFEREN := V_CREFEREN;	
                        :B620PSAC.AUX_FCADUCID := V_FCADUCID;
                        :B620PSAC.AUX_CNUMLOTE := V_CNUMLOTE;
                        :B620PSAC.AUX_CVARLOGI := V_CVARLOGI;
                        :B620PSAC.AUX_CINDUCON := V_CINDUCON;
                        :B620PSAC.AUX_XESTRCVL := V_XESTRCVL;
                        :B620PSAC.DESCRIPCION := V_DESCRIPCION;
                        :B620PSAC.AUX_LOTE := V_LOTE;
                        :B620PSAC.DESDE_FECHA :=  V_DESDE_FECHA;
                        :B620PSAC.HASTA_FECHA := V_HASTA_FECHA;
                    END IF;
  
		
END;